version: '3'
services:
  web :
    build :
      context: ./web
      args :
           NODE_ENV : production
           NODE_PORT : 4000
           DB_HOST : db
           DB_USER : root
           DB_PASSWORD : root
           DB_NAME : users
    ports:
      - "4000:4000"
  db:
    build :
      context: ./db
      args:
          MYSQL_DATABASE : users
          MYSQL_USER : root
          MYSQL_PASSWORD : root
          MYSQL_ROOT_PASSWORD : root
    expose:
      - "3306"