FROM mysql:5.7

ADD InitDatabase.sql /etc/mysql/InitDatabase.sql

RUN chown -R mysql:root /var/lib/mysql/

ARG MYSQL_DATABASE=scalab-users-service
ARG MYSQL_USER=root
ARG MYSQL_PASSWORD=root
ARG MYSQL_ROOT_PASSWORD=root

ENV MYSQL_DATABASE=$MYSQL_DATABASE
ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

RUN sed -i 's/MYSQL_DATABASE/'$MYSQL_DATABASE'/g' /etc/mysql/InitDatabase.sql && \
    sed -i 's/MYSQL_USER/'$MYSQL_USER'/g' /etc/mysql/InitDatabase.sql && \
    sed -i 's/MYSQL_PASSWORD/'$MYSQL_PASSWORD'/g' /etc/mysql/InitDatabase.sql

CMD ["mysqld", "--init-file=/etc/mysql/InitDatabase.sql"]
EXPOSE 3306 