CREATE DATABASE IF NOT EXISTS `MYSQL_DATABASE`;
GRANT ALL ON `MYSQL_DATABASE`.* TO 'MYSQL_USER'@'%' IDENTIFIED BY 'MYSQL_PASSWORD';

CREATE TABLE IF NOT EXISTS `MYSQL_DATABASE`.`t_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


INSERT INTO `MYSQL_DATABASE`.`t_users` (`login`) VALUES ('admin');

COMMIT;