apiVersion: v1
kind: Service
metadata:
  name: scalab-users-service-web
  namespace: scalab
  labels:
    app: scalab-users-service
spec:
  ports:
  - port: 80
    targetPort : 4000
  selector:
    app: scalab-users-service
    tier: web
  type : LoadBalancer
status:
  loadBalancer:
      ingress:
        - ip : 193.70.7.76
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scalab-users-service-web
  labels:
    app: scalab-users-service
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scalab-users-service
        tier: web
    spec:
      containers:
      - image: scalab-users-service-web:v0.0.2
        name: scalab-users-service-web