apiVersion: v1
kind: Service
metadata:
  name: scalab-users-service-db
  labels:
    app: scalab-users-service
spec:
  ports:
    - port: 3306
  selector:
    app: scalab-users-service
    tier: db
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scalab-users-service-db-pv-claim
  labels:
    app: scalab-users-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scalab-users-service-db
  labels:
    app: scalab-users-service
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scalab-users-service
        tier: db
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          # change this
          value: root
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: scalab-users-service-db-pv-claim